### ISSUE TITLE
Make z-Index of layers configurable

### ISSUE THREAD

**Issue by ischas** [KlausBenndorf/guide4you#204]
The display order should not dependend on the order in the layer configuration.

## Example:

Ortho and street names are configured as base layers, classification as feature layer. The street names should be displayed on top of the classification. (Possibly a work around: configure street names as fixed feature layer.)

![z-index](https://cloud.githubusercontent.com/assets/8558126/22201204/e7099368-e162-11e6-8be5-45c300921d50.png)

**Comment by penpendede** [comment]
Actually this already is available in the OpenLayers version we use. All one needs to do is set the layer's **zIndex** attribute. For illustration purposes I created branch named *zIndex* that (ab)uses the attribute so that *Roads and Labels for Hydda* only becomes visible if the base layer *OSM in Hydda* style is active.

**Comment by ischas** [comment]
Thx
